/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */
import type { DailyVisitorDto } from './dailyVisitorDto';
import type { AgeGroupGenderDtoGender } from './ageGroupGenderDtoGender';

export interface AgeGroupGenderDto {
  visitors: DailyVisitorDto[];
  gender: AgeGroupGenderDtoGender;
  localsCount: number;
  refugeesCount: number;
  locals: DailyVisitorDto;
  refugees: DailyVisitorDto;
}
