/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */

export type DailyVisitorDtoStatus = typeof DailyVisitorDtoStatus[keyof typeof DailyVisitorDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DailyVisitorDtoStatus = {
  Local: 'Local',
  Refugee: 'Refugee',
} as const;
