/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */
import type { DailyVisitorDto } from './dailyVisitorDto';
import type { MonthlyAgeGroupDtoGroup } from './monthlyAgeGroupDtoGroup';
import type { MonthlyAgeGroupDtoRange } from './monthlyAgeGroupDtoRange';
import type { AgeGroupGenderDto } from './ageGroupGenderDto';

export interface MonthlyAgeGroupDto {
  visitors: DailyVisitorDto[];
  group: MonthlyAgeGroupDtoGroup;
  range: MonthlyAgeGroupDtoRange;
  males: AgeGroupGenderDto;
  females: AgeGroupGenderDto;
}
