/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */

export type NewVisitorDtoStatus = typeof NewVisitorDtoStatus[keyof typeof NewVisitorDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NewVisitorDtoStatus = {
  Local: 'Local',
  Refugee: 'Refugee',
} as const;
