/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */
import type { NewVisitorDtoStatus } from './newVisitorDtoStatus';
import type { NewVisitorDtoGender } from './newVisitorDtoGender';

export interface NewVisitorDto {
  name: string;
  birthday: string;
  status: NewVisitorDtoStatus;
  gender: NewVisitorDtoGender;
  hasDisability: boolean;
}
