/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */

export type ReportControllerGetExtendedMonthlyReportParams = {
to: string;
from: string;
};
