/**
 * Generated by orval v6.12.1 🍺
 * Do not edit manually.
 * Vol
 * Registration api
 * OpenAPI spec version: 0.1
 */
import type { DailyVisitorDto } from './dailyVisitorDto';
import type { WeeklyAgeGroupDtoGroup } from './weeklyAgeGroupDtoGroup';
import type { WeeklyAgeGroupDtoRange } from './weeklyAgeGroupDtoRange';
import type { AgeGroupGenderDto } from './ageGroupGenderDto';

export interface WeeklyAgeGroupDto {
  visitors: DailyVisitorDto[];
  group: WeeklyAgeGroupDtoGroup;
  range: WeeklyAgeGroupDtoRange;
  males: AgeGroupGenderDto;
  females: AgeGroupGenderDto;
}
